version: '3.4'

services:
  fox-test.api:
    image: ${DOCKER_REGISTRY-}foxtestapi
    container_name: fox-test.api
    build:
      context: .
      dockerfile: FOX-TEST.API/Dockerfile
    depends_on:
      - db
      - redis
    networks:
      - db
      - redis
    links:
      - redis

  db:
    image: mysql:8
    container_name: db.mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - "MYSQL_ROOT_HOST=%"
    networks:
      - db

  redis:
    image: redis
    container_name: redis.cache
    networks:
      - redis
    ports:
      - "6379:6379"

networks:
  db:
  redis:


volumes:
  mariadb-data: